GRPC_PROTOC_PLUGIN=/Users/cex/.nuget/packages/grpc.tools/2.60.0/tools/macosx_x64/grpc_csharp_plugin
gen:
	protoc --csharp_out=. --grpc_out=. --plugin=protoc-gen-grpc=$(GRPC_PROTOC_PLUGIN) reverse.proto